// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwqzwwcblugblbbunicp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cXp3d2NibHVnYmxiYnVuaWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjI1NDAsImV4cCI6MjA2MDUzODU0MH0.Ciq8CKLdLrnpvxwRSDTUbtWGWsUklkYI8in-k629sCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);