// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdxysjdzuavmjcuwslol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkeHlzamR6dWF2bWpjdXdzbG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTkzNjAsImV4cCI6MjA2MDUzNTM2MH0.UugjkE_yboTCZyrNypvKjodSWOTyd6kDptbUey2cRPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);